baseURL = "https://www.trendfind.online/"
languageCode = "en-us"
title = "TrendFind"
theme = "PaperMod"
themesDir = "themes"
enableRobotsTXT = true
canonifyURLs = true
buildDrafts = false
buildFuture = false
buildExpired = false

[pagination]
  pagerSize = 10


[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
env = "production"
author = "TrendFind Autopilot"
description = "AI-powered daily insights on technology, innovation, and futurism."
keywords = ["AI", "Technology", "Innovation", "Futurism", "TrendFind"]
images = ["/images/default.jpg"]
DateFormat = "2006-01-02"
defaultTheme = "auto"
ShowReadingTime = true
ShowBreadCrumbs = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true
disableThemeToggle = false
ShowToc = false
UseHugoToc = false
mainSections = ["posts"]
ShowFullTextinRSS = true
homeInfoParams = false

[menu]
  [[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  identifier = "articles"
  name = "Articles"
  url = "/posts/"
  weight = 2

  [[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 3

[params.assets]
  css = ["css/stylesheet.css"]
